import { createRootRoute, HeadContent, Scripts, useParams } from "@tanstack/react-router";
import { IconEungyeole } from "@/components/assets/icon-eungyeole";
import globalsCss from "@/styles/globals.css?url";
import { DEFAULT_LOCALE, isLocale } from "@/utils/i18n/i18n";

export const Route = createRootRoute({
  head: () => ({
    meta: [
      { charSet: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { title: "안은결" },
      { name: "description", content: "Generated by create next app" },
    ],
    links: [
      { rel: "stylesheet", href: globalsCss },
      { rel: "icon", href: "/favicon.ico" },
    ],
  }),
  shellComponent: RootDocument,
  notFoundComponent: NotFound,
});

function RootDocument({ children }: Readonly<{ children: React.ReactNode }>) {
  const { lang } = useParams({ strict: false });

  return (
    <html lang={isLocale(lang) ? lang : DEFAULT_LOCALE}>
      <head>
        <HeadContent />
      </head>
      <body className="antialiased max-w-3xl mx-auto py-12 px-4 relative">
        {children}
        <Scripts />
      </body>
    </html>
  );
}

function NotFound() {
  return (
    <div className="z-50 fixed inset-0 bg-background text-base flex items-center justify-center">
      <div className="flex flex-col items-center justify-center gap-4">
        <IconEungyeole width={50} height={50} />
        <div className="flex flex-col items-center justify-center gap-2">
          <h1 className="text-2xl font-bold">404 Not Found</h1>
          <p className="text-sm text-gray-500">The page you are looking for does not exist.</p>
        </div>
      </div>
    </div>
  );
}
