"use client";

import { Check, Copy } from "lucide-react";
import { type CSSProperties, type FormEvent, useEffect, useState } from "react";

const PRODUCT_ORIGIN = "https://velog-readme-stats.vercel.app";
const DEFAULT_NAME = "eungyeole";
const DEFAULT_TAG = "github";
const TAG_FONT_FAMILY =
  "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji";

const PRODUCT_IMAGE_STYLE = {
  filter: "grayscale(1) sepia(0.14) saturate(0.72) brightness(1.04) contrast(0.94)",
  mixBlendMode: "multiply",
} satisfies CSSProperties;

const VARIANTS = [
  { id: "post", label: "Latest", path: "/api", width: 450, height: 130 },
  { id: "badge", label: "Badge", path: "/api/badge", width: 86, height: 20 },
  { id: "list", label: "List", path: "/api/list", width: 450, height: 160 },
] as const;

type Variant = (typeof VARIANTS)[number]["id"];

export function VelogStatsDemo() {
  const cardUrl = buildCardUrl("post", DEFAULT_NAME, DEFAULT_TAG);
  const destinationUrl = buildDestinationUrl(DEFAULT_NAME, DEFAULT_TAG);

  return (
    <section
      aria-label="Live Velog Readme Stats card"
      className="grid min-h-60 w-full place-items-center overflow-hidden rounded-2xl bg-preview-canvas p-5"
    >
      <a
        href={destinationUrl}
        target="_blank"
        rel="noopener noreferrer"
        aria-label="Open the post shown in this card"
        className="block !border-0"
      >
        <img
          alt="Latest Velog post generated by Velog Readme Stats"
          className="h-auto w-full max-w-[450px]"
          decoding="async"
          height={130}
          loading="lazy"
          src={cardUrl}
          style={PRODUCT_IMAGE_STYLE}
          width={450}
        />
      </a>
    </section>
  );
}

export function VelogStatsPlayground() {
  const [variant, setVariant] = useState<Variant>("post");
  const [draftName, setDraftName] = useState(DEFAULT_NAME);
  const [draftTag, setDraftTag] = useState(DEFAULT_TAG);
  const [query, setQuery] = useState({ name: DEFAULT_NAME, tag: DEFAULT_TAG });
  const [copied, setCopied] = useState(false);
  const activeVariant = VARIANTS.find((item) => item.id === variant) ?? VARIANTS[0];
  const cardUrl = buildCardUrl(variant, query.name, query.tag);
  const destinationUrl = buildDestinationUrl(query.name, variant === "post" ? query.tag : "");
  const markdown = `[![Velog's GitHub stats](${cardUrl})](${destinationUrl})`;

  const applyQuery = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setQuery({
      name: draftName.trim().replace(/^@/, "") || DEFAULT_NAME,
      tag: draftTag.trim().replace(/^#/, ""),
    });
  };

  const copyMarkdown = async () => {
    await navigator.clipboard.writeText(markdown);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1500);
  };

  return (
    <section
      aria-label="Velog Readme Stats playground"
      className="overflow-hidden rounded-lg border border-preview-border bg-preview-surface text-preview-strong"
    >
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-preview-border p-3">
        <div aria-label="Card type" className="flex rounded-md bg-preview-canvas p-0.5" role="tablist">
          {VARIANTS.map((item) => (
            <button
              aria-selected={variant === item.id}
              className={`rounded-[0.3rem] px-2.5 py-1.5 text-xs transition-colors ${
                variant === item.id
                  ? "bg-preview-surface text-preview-strong shadow-sm"
                  : "text-preview-muted hover:text-preview-strong"
              }`}
              key={item.id}
              onClick={() => setVariant(item.id)}
              role="tab"
              type="button"
            >
              {item.label}
            </button>
          ))}
        </div>

        <form className="flex min-w-0 flex-1 justify-end gap-2" onSubmit={applyQuery}>
          <label className="flex min-w-0 max-w-36 items-center rounded-md border border-preview-border bg-background px-2 text-xs text-preview-muted">
            <span aria-hidden="true">@</span>
            <span className="sr-only">Velog username</span>
            <input
              aria-label="Velog username"
              className="min-w-0 flex-1 bg-transparent py-1.5 text-preview-strong outline-none"
              onChange={(event) => setDraftName(event.currentTarget.value)}
              spellCheck="false"
              value={draftName}
            />
          </label>

          {variant === "post" ? (
            <label className="hidden min-w-0 max-w-28 items-center rounded-md border border-preview-border bg-background px-2 text-xs text-preview-muted sm:flex">
              <span aria-hidden="true">#</span>
              <span className="sr-only">Optional Velog tag</span>
              <input
                aria-label="Optional Velog tag"
                className="min-w-0 flex-1 bg-transparent py-1.5 text-preview-strong outline-none"
                onChange={(event) => setDraftTag(event.currentTarget.value)}
                spellCheck="false"
                value={draftTag}
              />
            </label>
          ) : null}

          <button
            className="rounded-md bg-preview-strong px-3 py-1.5 text-xs font-medium text-preview-surface transition-opacity hover:opacity-80"
            type="submit"
          >
            Apply
          </button>
        </form>
      </div>

      <div aria-live="polite" className="grid min-h-64 place-items-center bg-preview-canvas p-6">
        <a
          href={destinationUrl}
          target="_blank"
          rel="noopener noreferrer"
          aria-label="Open the generated Velog result"
          className="block !border-0"
        >
          <img
            alt={`Velog Readme Stats ${activeVariant.label.toLowerCase()} result for ${query.name}`}
            className="h-auto max-h-52 max-w-full"
            height={activeVariant.height}
            key={cardUrl}
            src={cardUrl}
            style={PRODUCT_IMAGE_STYLE}
            width={activeVariant.width}
          />
        </a>
      </div>

      <div className="flex items-center gap-3 border-t border-preview-border px-3 py-2.5">
        <code className="min-w-0 flex-1 truncate border-0 bg-transparent p-0 text-[11px] text-preview-muted">
          {markdown}
        </code>
        <button
          aria-label="Copy Markdown"
          className="grid size-7 shrink-0 place-items-center rounded-md text-preview-muted transition-colors hover:bg-preview-canvas hover:text-preview-strong"
          onClick={copyMarkdown}
          type="button"
        >
          {copied ? (
            <Check aria-hidden="true" className="size-3.5" />
          ) : (
            <Copy aria-hidden="true" className="size-3.5" />
          )}
        </button>
      </div>
    </section>
  );
}

export function VelogTagWidthDemo() {
  const [tag, setTag] = useState("TypeScript");
  const [textWidth, setTextWidth] = useState(58);

  useEffect(() => {
    const context = document.createElement("canvas").getContext("2d");
    if (!context) return;

    context.font = `12px ${TAG_FONT_FAMILY}`;
    setTextWidth(context.measureText(tag).width);
  }, [tag]);

  const tagWidth = Math.max(20, textWidth + 20);

  return (
    <section
      aria-label="SVG tag width playground"
      className="overflow-hidden rounded-lg border border-preview-border bg-preview-surface text-preview-strong"
    >
      <div className="grid min-h-48 place-items-center overflow-x-auto bg-preview-canvas p-6">
        <div className="min-w-max text-center">
          <svg
            aria-label={`${tag || "Empty"} tag, ${tagWidth.toFixed(1)} pixels wide`}
            height="20"
            role="img"
            style={{ fontFamily: TAG_FONT_FAMILY }}
            viewBox={`0 0 ${tagWidth} 20`}
            width={tagWidth}
          >
            <rect
              fill="transparent"
              height="19"
              rx="9.5"
              stroke="var(--preview-border)"
              width={Math.max(19, tagWidth - 1)}
              x="0.5"
              y="0.5"
            />
            <text fill="var(--preview-strong)" fontSize="12" textAnchor="middle" x={tagWidth / 2} y="13.5">
              {tag}
            </text>
          </svg>

          <p className="mt-5 font-mono text-[11px] tabular-nums text-preview-muted">
            {textWidth.toFixed(1)}px + 20px = {tagWidth.toFixed(1)}px
          </p>
        </div>
      </div>

      <label className="flex items-center gap-3 border-t border-preview-border px-4 py-3 text-xs text-preview-muted">
        <span>Tag</span>
        <input
          aria-label="Tag text"
          className="min-w-0 flex-1 bg-transparent text-preview-strong outline-none"
          maxLength={32}
          onChange={(event) => setTag(event.currentTarget.value)}
          spellCheck="false"
          value={tag}
        />
      </label>
    </section>
  );
}

function buildCardUrl(variant: Variant, name: string, tag: string) {
  const activeVariant = VARIANTS.find((item) => item.id === variant) ?? VARIANTS[0];
  const query = new URLSearchParams({ name });

  if (variant === "post" && tag) query.set("tag", tag);

  return `${PRODUCT_ORIGIN}${activeVariant.path}?${query.toString()}`;
}

function buildDestinationUrl(name: string, tag: string) {
  if (!tag) return `https://velog.io/@${encodeURIComponent(name)}`;

  const query = new URLSearchParams({ name, tag });
  return `${PRODUCT_ORIGIN}/api/redirect?${query.toString()}`;
}
