import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { ThemeSwitch } from "./_components/theme-switch";
import { Tabs, TabsList, TabsTab } from "@/components/ui/tabs";
import { Cuboid, SwatchBook, UserIcon } from "lucide-react";
import { Footer } from "@/components/footer/footer";
import { Navigation } from "./_components/navigation";

const pretendard = localFont({
  src: "../fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
});

export const metadata: Metadata = {
  title: "안은결",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pretendard.className} antialiased max-w-3xl mx-auto py-12 px-4 relative`}
      >
        {/* <ThemeSwitch /> */}
        <header className="flex flex-col gap-6">
          <div className="flex flex-col">
            <h1 className="text-md font-semibold">Eungyeole</h1>
            <p className="text-sm font-medium text-gray-500">
              Frontend Engineer
            </p>
          </div>
          <div className="-mx-1">
            <Navigation />
          </div>
        </header>
        <div className="mt-8">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
