import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { ThemeSwitch } from "./_components/theme-switch";

const pretendard = localFont({
  src: "../fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pretendard.className} antialiased max-w-3xl mx-auto py-12 px-4 relative`}
      >
        <ThemeSwitch />
        <div className="flex flex-col gap-0.5">
          <h1 className="text-md font-semibold">안은결</h1>
          <p className="text-sm font-medium text-gray-500">
            Frontend Developer
          </p>
        </div>
        {children}
      </body>
    </html>
  );
}
