/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangPingRouteImport } from './routes/$lang/ping'
import { Route as LangSandboxIndexRouteImport } from './routes/$lang/sandbox/index'
import { Route as LangArticleIndexRouteImport } from './routes/$lang/article/index'
import { Route as LangArticleSplatRouteImport } from './routes/$lang/article/$'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPingRoute = LangPingRouteImport.update({
  id: '/ping',
  path: '/ping',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangSandboxIndexRoute = LangSandboxIndexRouteImport.update({
  id: '/sandbox/',
  path: '/sandbox/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangArticleIndexRoute = LangArticleIndexRouteImport.update({
  id: '/article/',
  path: '/article/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangArticleSplatRoute = LangArticleSplatRouteImport.update({
  id: '/article/$',
  path: '/article/$',
  getParentRoute: () => LangRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/$lang/ping': typeof LangPingRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/article/$': typeof LangArticleSplatRoute
  '/$lang/article/': typeof LangArticleIndexRoute
  '/$lang/sandbox/': typeof LangSandboxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$lang/ping': typeof LangPingRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/article/$': typeof LangArticleSplatRoute
  '/$lang/article': typeof LangArticleIndexRoute
  '/$lang/sandbox': typeof LangSandboxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/$lang/ping': typeof LangPingRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/article/$': typeof LangArticleSplatRoute
  '/$lang/article/': typeof LangArticleIndexRoute
  '/$lang/sandbox/': typeof LangSandboxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$'
    | '/$lang/ping'
    | '/$lang/'
    | '/$lang/article/$'
    | '/$lang/article/'
    | '/$lang/sandbox/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/$lang/ping'
    | '/$lang'
    | '/$lang/article/$'
    | '/$lang/article'
    | '/$lang/sandbox'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$'
    | '/$lang/ping'
    | '/$lang/'
    | '/$lang/article/$'
    | '/$lang/article/'
    | '/$lang/sandbox/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/ping': {
      id: '/$lang/ping'
      path: '/ping'
      fullPath: '/$lang/ping'
      preLoaderRoute: typeof LangPingRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/sandbox/': {
      id: '/$lang/sandbox/'
      path: '/sandbox'
      fullPath: '/$lang/sandbox/'
      preLoaderRoute: typeof LangSandboxIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/article/': {
      id: '/$lang/article/'
      path: '/article'
      fullPath: '/$lang/article/'
      preLoaderRoute: typeof LangArticleIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/article/$': {
      id: '/$lang/article/$'
      path: '/article/$'
      fullPath: '/$lang/article/$'
      preLoaderRoute: typeof LangArticleSplatRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangRouteRouteChildren {
  LangPingRoute: typeof LangPingRoute
  LangIndexRoute: typeof LangIndexRoute
  LangArticleSplatRoute: typeof LangArticleSplatRoute
  LangArticleIndexRoute: typeof LangArticleIndexRoute
  LangSandboxIndexRoute: typeof LangSandboxIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangPingRoute: LangPingRoute,
  LangIndexRoute: LangIndexRoute,
  LangArticleSplatRoute: LangArticleSplatRoute,
  LangArticleIndexRoute: LangArticleIndexRoute,
  LangSandboxIndexRoute: LangSandboxIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
  SplatRoute: SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
